### ISSUE TITLE
Before you get too far in

### ISSUE THREAD

**Issue by johnroper100** [TGWaffles/uDMX-Lighting-CHS-Controller#1]
I just wanted to share my project that is built for schools and small venues using uDMX: [https://github.com/johnroper100/Tonalite](https://github.com/johnroper100/Tonalite)

**Comment by TGWaffles** [comment]
Hi there.

I'm developing this separately as a challenge and for experience. We're also making it bespoke for our setup, so that there's no fiddling or setup involved and it just works, along with any modifications we might feel like adding - after developing your own tool it's much easier to add features to something you completely understand rather than someone else's tools.

Your tool does look interesting though - I might refer to it in the future if things get messy!
